26 awaiting reveiw + article page
yalla-coop/working-class-history pull request #43
Opened 2021-10-21 13:30 UTC by fadeomar

#### Issues this PR relates to
#26 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-10-31 15:10 UTC, RamyAlshurafa requested changes
- [x] `Continue reading...` font weight should be 700
- [ ] spacing between each articles should be 80px
- [x] in article page, date font size doesn't match figma
![image](https://user-images.githubusercontent.com/34629478/139589847-d1bc0d8b-5301-4ed3-bb8d-22a7da60e438.png)
- [ ] date component should has higher z index 
![image](https://user-images.githubusercontent.com/34629478/139589978-13834044-1b02-483b-b577-d0aaf984f4d2.png)
 - [ ] return home button should take me to awaiting review list again

2021-10-31 15:22 UTC, RamyAlshurafa requested changes
- [ ] buttons need right padding on smaller screens
![image](https://user-images.githubusercontent.com/34629478/139590206-8c1e4513-3a49-49d8-9fe5-ac0f6b82fb2a.png)

2021-10-31 15:22 UTC, RamyAlshurafa commented on client/src/pages/ArticlePage/index.js
> +        console.log({ data });
```suggestion
```

2021-10-31 15:22 UTC, RamyAlshurafa commented on client/src/pages/ArticlePage/index.js
> +        console.log({ data });
```suggestion
```

2021-10-31 15:22 UTC, RamyAlshurafa commented on client/src/pages/EditEventPage/style.js
> +export const Form = styled.form``;
i cant see where this been used

2021-11-01 08:36 UTC, fadeomar commented on client/src/pages/EditEventPage/style.js
> +export const Form = styled.form``;
C:\Users\Lenovo\Desktop\code\working-class-history\client\src\pages\EditEventPage\ContributeForm.js

2021-11-01 08:36 UTC, fadeomar commented on client/src/pages/ArticlePage/index.js
> +        console.log({ data });
done

2021-11-01 08:36 UTC, fadeomar commented on client/src/pages/ArticlePage/index.js
> +        console.log({ data });
done

2021-11-01 13:28 UTC, RamyAlshurafa requested changes
![image](https://user-images.githubusercontent.com/34629478/139679222-67cfa62a-4ea3-4018-96af-a394e9de2aed.png)

2021-11-02 09:53 UTC, RamyAlshurafa approved these changes

2021-11-02 09:53 UTC, merged