27 awiting review and tag page api call
yalla-coop/working-class-history pull request #48
Opened 2021-10-31 15:13 UTC by fadeomar

#### Issues this PR relates to
#27
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-11-02 13:46 UTC, RamyAlshurafa requested changes
- [ ] page doesn't show data,and the request gets 404 error 
![image](https://user-images.githubusercontent.com/34629478/139858402-6db17aef-641b-4870-9f8e-940f65bc7b47.png)

2021-11-02 13:46 UTC, RamyAlshurafa commented on client/src/api-calls/Article/index.js
> +      `${DB_ROWS_TABLE}/${apiData.TABLES.articles}?user_field_names=true&order_by=created_at&filter__field_177157__single_select_equal=${apiData.STATUS.published}`
store columns in object, and refactore all existing code please
```suggestion
      `${DB_ROWS_TABLE}/${apiData.TABLES.articles}?user_field_names=true&order_by=created_at&filter__${apiData.COLUMNS.STATUS}__single_select_equal=${apiData.STATUS.published}`
```

2021-11-02 13:46 UTC, RamyAlshurafa commented on client/src/components/Tags/TagList/index.js
> +            <T.P>{tag.label || tag.Title}</T.P>
why label is lower case whilst Title is upper case?

2021-11-02 13:46 UTC, RamyAlshurafa commented on client/src/pages/CategoryPage/index.js
> +      tags.filter((tag) =>
```suggestion
      tags?.filter((tag) =>
```

2021-11-03 07:45 UTC, fadeomar commented on client/src/components/Tags/TagList/index.js
> +            <T.P>{tag.label || tag.Title}</T.P>
because the label is property from dummy data and Title comes from the backend, so I just kept it here for not to break the parts that need to connect with backend first

2021-11-03 09:06 UTC, fadeomar commented on client/src/pages/CategoryPage/index.js
> +      tags.filter((tag) =>
done

2021-11-03 09:26 UTC, fadeomar commented on client/src/api-calls/Article/index.js
> +      `${DB_ROWS_TABLE}/${apiData.TABLES.articles}?user_field_names=true&order_by=created_at&filter__field_177157__single_select_equal=${apiData.STATUS.published}`
done

2021-11-03 09:26 UTC, fadeomar commented on client/src/components/Tags/TagList/index.js
> +            <T.P>{tag.label || tag.Title}</T.P>
this will be updated on next PR

2021-11-03 15:08 UTC, RamyAlshurafa approved these changes

2021-11-03 15:08 UTC, merged

2021-11-03 15:10 UTC, fadeomar commented on client/src/api-calls/Tag/index.js
> +      `${DB_ROWS_TABLE}/${apiData.TABLES.tags}/?user_field_names=true&filter__field_177168__single_select_equal=${category}`
update this