28 backend for creating an authenticating user
yalla-coop/working-class-history pull request #49
Opened 2021-11-02 10:44 UTC by fadeomar

#### Issues this PR relates to
closes : #28
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-11-02 14:06 UTC, RamyAlshurafa requested changes
- [ ] sign up / login pages shouldn't be accessible by logged in users
- [ ] in the issue it says "Whenever they go to protected pages, on first app load check if they have pin in cookie and **check against Baserow** for pin and approved"

2021-11-02 14:06 UTC, RamyAlshurafa commented on client/src/helpers/unique-id.js
> +function uniqueID() {
also rename the file, and its calls
```suggestion
function createUniqueID() {
```

2021-11-02 14:06 UTC, RamyAlshurafa commented on client/src/App.js
> +        <AuthProvider>
don't wrap everything in authProvider, just put it around the protected routes

2021-11-02 16:07 UTC, fadeomar commented on client/src/helpers/unique-id.js
> +function uniqueID() {
done

2021-11-02 16:16 UTC, fadeomar commented on client/src/components/Route/index.js
> +        <Component {...props} user={user} />
done

2021-11-02 17:05 UTC, fadeomar commented on client/src/App.js
> +        <AuthProvider>
done

2021-11-02 17:14 UTC, fadeomar commented on client/src/context/auth.js
> +  full_name: '',
done

2021-11-03 10:28 UTC, RamyAlshurafa approved these changes

2021-11-03 10:28 UTC, merged