29 backend articles
yalla-coop/working-class-history pull request #50
Opened 2021-11-03 16:04 UTC by fadeomar

#### Issues this PR relates to
#29 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-11-04 14:29 UTC, RamyAlshurafa requested changes
- [ ] page content shows html tags
![image](https://user-images.githubusercontent.com/34629478/140330115-284a1bc3-717e-4a0c-a6cf-ce101b3e892d.png)
- [ ] date is not formatted correctly + should be event date not created at 
![image](https://user-images.githubusercontent.com/34629478/140330983-7fd3d6f4-8c93-40f5-b32d-9dd329342e1f.png)
- [ ] author should be link if author link is provided
![image](https://user-images.githubusercontent.com/34629478/140332092-28b9dc0a-68e0-4564-aed7-a0041d138858.png)

2021-11-07 09:28 UTC, thejoefriel commented
Rich text isn't being rendered properly on preview, it's showing tags. Should remove the tags: 
![image](https://user-images.githubusercontent.com/19708921/140639607-769e5a53-125b-472e-8ecf-c17f14c5eb4f.png)

Also doesn't render it properly on the article. This should use the html to render the style as the user wanted it to look

2021-11-07 11:37 UTC, thejoefriel requested changes
- [ ] Too many lines in preview. Make no more than 4 lines. Also seems to be showing up too small and not in line with typography on wireframes
![image](https://user-images.githubusercontent.com/19708921/140643073-1b2b9f57-a5b2-4145-b23c-23b52f5fc5e7.png)

- [ ] Published a new article but didn't show up at the top of the home page under latest. Latest should be latest articles published

- [ ] Title isn't showing on new articles 
![image](https://user-images.githubusercontent.com/19708921/140643248-3ddb8021-453f-4542-8d17-541e6e73992b.png)

- [ ] Also (related to image above) the way you are rendering text for submitted articles is not consistent with the style. You need to make sure that even when rendering html elements, you then still ensure they are following the same typography (so for example, ensuring <p> elements use T.P OR change the global style to ensure consistency. At the moment you can see it's clearly different.  

- [ ] Related to image above, social icons should line up with the top of the first line of the description when there's no image. At the moment it seems to be further down.

2021-11-09 17:50 UTC, thejoefriel approved these changes

2021-11-09 17:50 UTC, merged